# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment: 
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Pa55w0rd@2019"
    ports:
      - "1433:1433"
    
  catalogapi:
    image: catalogapi
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8090:80"
    depends_on:
            - db